#!/usr/bin/env node

/**
 * GitHub Starred Repos → Markdown 导出脚本
 *
 * 用法:
 *   node export.mjs
 *
 * 环境变量:
 *   GITHUB_TOKEN — GitHub Personal Access Token (需要 repo 或 public_repo 权限)
 *
 * 可选环境变量:
 *   MAX_REPOS — 最大导出仓库数 (默认: 0 = 全部)
 *   OUTPUT_FILE — 输出文件路径 (默认: ./github-starred-repos-YYYY-MM-DD.md)
 *
 * 逻辑参考:
 *   - api/src/user-export.ts  (Markdown 生成格式)
 *   - api/src/user-sync.ts    (GitHub API 分页拉取逻辑)
 */

import { createWriteStream } from "node:fs";
import { writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";

// ==================== 配置 ====================

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const PER_PAGE = 100; // GitHub API 每页最大 100 条
const MAX_REPOS = parseInt(process.env.MAX_REPOS || "0", 10) || Infinity;
const GITHUB_API = "https://api.github.com";

// ==================== 工具函数 ====================

/** 解析 GitHub Link 响应头，提取 rel→URL 映射 */
function parseLinkHeader(header) {
  const links = {};
  for (const part of header.split(",")) {
    const section = part.split(";");
    if (section.length !== 2) continue;
    const url = section[0].replace(/<|>/g, "").trim();
    const name = section[1].replace(/rel="|"/g, "").trim();
    links[name] = url;
  }
  return links;
}

/** 格式化 Stars 数量（1.2k / 310 等） */
function formatStars(count) {
  if (count >= 1000) {
    const k = count / 1000;
    return k >= 10
      ? `${Math.round(k)}k`
      : `${(Math.round(k * 10) / 10).toFixed(1).replace(/\.0$/, "")}k`;
  }
  return String(count);
}

/** 格式化 ISO 日期字符串 → YYYY-MM-DD */
function formatDate(isoStr) {
  return isoStr ? isoStr.split("T")[0] : "N/A";
}

/** 转义 Markdown 表格中的特殊字符 */
function escapeMarkdown(text) {
  if (!text) return "";
  return text
    .replace(/\|/g, "\\|")
    .replace(/\n/g, " ")
    .replace(/\r/g, "");
}

// ==================== GitHub API 调用 ====================

/**
 * 获取用户 GitHub Stars 列表（按 starred_at 降序分页拉取）
 *
 * 参考: api/src/user-sync.ts → fetchUserStarredList()
 */
async function fetchStarredRepos({ maxRepos = Infinity, onProgress } = {}) {
  const allRepos = [];
  let page = 1;
  let hasMore = true;

  while (hasMore && allRepos.length < maxRepos) {
    const url = `${GITHUB_API}/user/starred?per_page=${PER_PAGE}&page=${page}&sort=created&direction=desc`;

    const response = await fetch(url, {
      headers: {
        Accept: "application/vnd.github.v3.star+json",
        Authorization: `Bearer ${GITHUB_TOKEN}`,
        "User-Agent": "GitHub-Star-Export/1.0",
        "X-GitHub-Api-Version": "2022-11-28",
      },
    });

    if (!response.ok) {
      const text = await response.text();
      if (response.status === 401) {
        throw new Error(
          `GitHub API 认证失败 (401): 请检查 GITHUB_TOKEN 是否有效。\n` +
            `访问 https://github.com/settings/tokens 验证你的 Token。`
        );
      }
      if (response.status === 403) {
        throw new Error(
          `GitHub API 访问被拒绝 (403): 可能是速率限制或权限不足。\n` +
            `请确保 Token 具有 repo 或 public_repo 权限。`
        );
      }
      throw new Error(`GitHub API error ${response.status}: ${text}`);
    }

    const entries = await response.json();

    if (entries.length === 0) {
      hasMore = false;
      break;
    }

    // 检查是否超过上限
    const remaining = maxRepos - allRepos.length;
    const toAdd = entries.slice(0, Math.min(remaining, entries.length));
    allRepos.push(...toAdd);

    if (allRepos.length >= maxRepos) {
      break;
    }

    // 通过 Link 响应头判断是否有下一页
    const linkHeader = response.headers.get("Link");
    if (linkHeader) {
      const links = parseLinkHeader(linkHeader);
      hasMore = "next" in links;
    } else {
      hasMore = entries.length === PER_PAGE;
    }

    page++;

    if (onProgress) {
      onProgress({
        fetched: allRepos.length,
        page,
        hasMore,
      });
    }
  }

  return allRepos;
}

// ==================== Markdown 生成 ====================

/**
 * 生成 Markdown 文件内容
 *
 * 参考: api/src/user-export.ts → generateMarkdown() — 免费用户表格看板风格
 */
function generateMarkdown(repos) {
  const lines = [];
  const exportDate = new Date().toISOString().split("T")[0];
  const totalStars = repos.reduce(
    (sum, r) => sum + (r.repo.stargazers_count || 0),
    0
  );

  // 标题区
  lines.push("# 📂 My GitHub Starred Repositories");
  lines.push("");
  lines.push(
    `**Export Date**: ${exportDate}　|　**Repos**: ${repos.length}　|　**Total Stars**: ${totalStars.toLocaleString()}`
  );
  lines.push("");
  lines.push(
    `> Generated by [GitHub Star Export](https://github.com/mktime/github-repo-backup) — a free tool to backup your GitHub stars.`
  );
  lines.push(
    `> 💡 Need AI-powered categorization, automatic sync, or weekly reports? Visit **[mktime.org](https://mktime.org)** for the full experience.`
  );
  lines.push("");

  // 目录
  lines.push("## 📋 Table of Contents");
  lines.push("");
  lines.push("- [Repository List](#-repository-list)");
  lines.push("");
  lines.push("---");
  lines.push("");

  // 仓库表格
  lines.push("## 📜 Repository List");
  lines.push("");
  lines.push("| # | Repository | Stars | Language | Starred At |");
  lines.push("| :---: | :--- | :---: | :---: | :---: |");

  repos.forEach((entry, index) => {
    const repo = entry.repo;
    const desc = repo.description
      ? ` — ${escapeMarkdown(repo.description)}`
      : "";
    const lang = repo.language || "";
    const starredAt = formatDate(entry.starred_at);

    lines.push(
      `| ${index + 1} | [**${escapeMarkdown(repo.full_name)}**](${repo.html_url})${desc} | ⭐ ${formatStars(repo.stargazers_count)} | ${lang} | ${starredAt} |`
    );
  });

  lines.push("");

  // 页脚
  lines.push("---");
  lines.push("");
  lines.push(
    `*Exported on ${exportDate} · ${repos.length} repositories · Powered by [GitHub Star Export](https://mktime.org)*`
  );

  return lines.join("\n");
}

// ==================== 主流程 ====================

async function main() {
  // 1. 检查 Token
  if (!GITHUB_TOKEN) {
    console.error(`
💡 需要配置 GitHub 访问权限

为了能帮你导出 GitHub 仓库，我需要一个具有读取权限的 Personal Access Token (PAT)。请放心，这个 Token 会安全地保存在你的本地环境中，我不会上传到任何第三方服务器。

第一步：获取 Token

    访问 GitHub Token Settings:
    https://github.com/settings/tokens

    点击 Generate new token (classic)。

    勾选 repo 权限（如果只需要公开仓库，可以只勾选 public_repo）。

    点击生成并复制该 Token（关闭页面后将无法再次查看）。

第二步：设置环境变量
请在终端中运行以下命令（将 你的_token 替换为刚才复制的内容）：

    export GITHUB_TOKEN="你的_token"

    或者将上面这行加入 ~/.bashrc / ~/.zshrc 以持久化保存。

设置完成后，重新运行本脚本即可：

    node export.mjs
`);
    process.exit(1);
  }

  // 2. 确定输出路径
  const timestamp = new Date().toISOString().split("T")[0];
  const outputFile = resolve(
    process.env.OUTPUT_FILE || `./github-starred-repos-${timestamp}.md`
  );

  // 确保输出目录存在
  const dir = dirname(outputFile);
  await mkdir(dir, { recursive: true });

  // 3. 拉取 Star 仓库
  console.log("🔍 正在获取你的 GitHub Starred 仓库...\n");

  const maxRepos = MAX_REPOS || Infinity;
  const maxLabel = maxRepos === Infinity ? "全部" : `最多 ${maxRepos} 个`;

  let repos;
  try {
    repos = await fetchStarredRepos({
      maxRepos,
      onProgress: ({ fetched, page, hasMore }) => {
        process.stdout.write(
          `\r   📥 已获取: ${fetched} 个仓库 (第 ${page} 页)${hasMore ? " ..." : ""}`
        );
      },
    });
    console.log(""); // 换行
  } catch (err) {
    console.error(`\n❌ 拉取失败: ${err.message}`);
    process.exit(1);
  }

  if (repos.length === 0) {
    console.log("😕 你的 GitHub 账户还没有 Star 任何仓库。");
    console.log("   去逛逛 https://github.com，给有趣的项目点个 Star 吧！");
    process.exit(0);
  }

  // 4. 生成 Markdown
  console.log(`\n📝 正在生成 Markdown (共 ${repos.length} 个仓库)...`);
  const markdown = generateMarkdown(repos);

  // 5. 写入文件
  await writeFile(outputFile, markdown, "utf-8");
  const fileSizeKB = (Buffer.byteLength(markdown, "utf-8") / 1024).toFixed(1);

  console.log(`\n✅ 导出完成！`);
  console.log(`   📄 文件: ${outputFile}`);
  console.log(`   📦 仓库数: ${repos.length}`);
  console.log(`   📏 文件大小: ${fileSizeKB} KB`);
  console.log("");
  console.log(
    "💡 提示：如果你需要更强大的功能："
  );
  console.log("");
  console.log(
    "   🤖 AI 智能分类 — 自动将仓库归入 21 个技术分类"
  );
  console.log(
    "   🏷️  AI 标签生成 — 为每个仓库生成精准的技术标签"
  );
  console.log(
    "   📝 AI 一句话摘要 — 中英双语摘要，快速了解仓库用途"
  );
  console.log(
    "   🔄 自动定时同步 — 每天自动备份最新 Star，无需手动操作"
  );
  console.log(
    "   📊 每周周报 — 每周推送你 Star 了哪些新项目"
  );
  console.log(
    "   🌐 精美 Web 界面 — Bauhaus 风格仪表盘，搜索/筛选/浏览"
  );
  console.log("");
  console.log(
    "   👉 欢迎访问 https://mktime.org 体验完整功能！"
  );
}

main().catch((err) => {
  console.error("❌ 意外错误:", err);
  process.exit(1);
});
